name: CI/CD Pipeline for Elanguages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_API: elanacr.azurecr.io/elan-api:latest
      IMAGE_ESOLANG_API: elanacr.azurecr.io/elan-esolang-api:latest
      IMAGE_SITE: elanacr.azurecr.io/elan-site:latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. (Optional) Set up Node if building the SITE (or API) locally
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # 3. Build the API image
      - name: Build API Docker Image
        run: |
          docker build -t $IMAGE_API -f ./ELAN.Api/Dockerfile ./ELAN.Api

      - name: Build ESOLANG API Docker Image
        run: |
          docker build -t $IMAGE_ESOLANG_API -f ./Elan.Api.Esolang/Dockerfile ./Elan.Api.Esolang

      # 4. Build the SITE image
      - name: Build SITE Docker Image
        run: |
          docker build -t $IMAGE_SITE -f ./FrontEnd/Dockerfile ./FrontEnd

      # 5. Login to Azure (using a Service Principal)
      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 6. Login to Azure Container Registry
      - name: Log in to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 7. Push API, ESOLANG API and SITE images to ACR
      - name: Push API Docker Image
        run: docker push $IMAGE_API

      - name: Push ESOLANG API Docker Image
        run: docker push $IMAGE_ESOLANG_API

      - name: Push SITE Docker Image
        run: docker push $IMAGE_SITE

      # 8. Set up AKS context so kubectl works with your cluster
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          cluster-name: elan-aks-cluster
          resource-group: elanResourceGroup

      # 9. Update Kubernetes manifests (Deployment, Ingress, etc.)
      - name: Deploy to AKS
        run: |
          kubectl apply -f devops/k8s/
