apiVersion: apps/v1
kind: Deployment
metadata:
  name: elan-site-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elan-site
  template:
    metadata:
      labels:
        app: elan-site
    spec:
      containers:
        - name: elan-site
          image: elanacr.azurecr.io/elan-site:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: elan-site-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: elan-site
